name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nodejs
      run: |
        sudo apt-get update 
        sudo apt-get -yq install curl gnupg
        curl -sL https://deb.nodesource.com/setup_12.x  | sudo bash
        sudo apt-get -yq install nodejs
    # install dependencies
    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run coverage

    - name: Clean up coverage
      run:  rm -rf coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "transaction-runner-liv" #Must be unique in Heroku
          heroku_email: "bestbrain10@gmail.com"